# Generated by Django 5.1.5 on 2025-01-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=15, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "cargo",
                    models.CharField(max_length=100, verbose_name="Cargo desejado"),
                ),
                (
                    "escolaridade",
                    models.CharField(
                        choices=[
                            ("ensino_medio_incompleto", "Ensino médio incompleto"),
                            ("ensino_medio_completo", "Ensino médio completo"),
                            (
                                "ensino_superior_incompleto",
                                "Ensino superior incompleto",
                            ),
                            ("ensino_superior_completo", "Ensino superior completo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("obs", models.CharField(max_length=150, verbose_name="Observações")),
                ("arquivo", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
