# Generated by Django 5.1.5 on 2025-01-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastroCV", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="obs",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Observações"
            ),
        ),
    ]
