# Generated by Django 5.1.5 on 2025-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCV', '0002_alter_formulario_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='telefone',
            field=models.CharField(max_length=9, verbose_name='Telefone'),
        ),
    ]
