# Generated by Django 5.1.5 on 2025-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCV', '0003_alter_formulario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='telefone',
            field=models.CharField(max_length=12, verbose_name='Telefone'),
        ),
    ]
