# Generated by Django 5.1.5 on 2025-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCV', '0004_alter_formulario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
