# Generated by Django 5.1.5 on 2025-01-27 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastroCV", "0006_formulario_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="data_envio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data e Hora do Envio"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP do Usuário"
            ),
        ),
    ]
