# Generated by Django 5.1.5 on 2025-01-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastroCV", "0007_formulario_data_envio_alter_formulario_ip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formulario",
            old_name="data_envio",
            new_name="dh",
        ),
    ]
